### ISSUE TITLE
Support for uppercase docker image name

### ISSUE THREAD

**Issue by patrikfejda** [FIIT-Databases/tester#1]
This may be rather a nice2have feature rather than a bug.

First time when I tried the tester, I was lazy and didnt want to copy the image name from workflows so I just took the repository name from URL:
![image](https://user-images.githubusercontent.com/55843553/219603439-5b17f537-f30f-45b7-bcc1-506916ca2d8f.png)

And I pasted it to the tester (with the capital letters):
![image](https://user-images.githubusercontent.com/55843553/219603172-1e85a47e-1da6-467b-9484-96e38dd7b5ba.png)

Runner didnt support the docker image name with capital letters and returned an error:
![image](https://user-images.githubusercontent.com/55843553/219603257-aa08b38f-11b4-4f3b-a4cc-d59fce2b1e03.png)

I would like to suggest to add `toLowerCase()` function on the form when Submitting the image name.

**Comment by Sibyx** [comment]
Hello @patrikfejda, thank you for reporting the issue. Your enhancement makes sense and will be implemented in the next release. I would like to ask you to write issues in English (this repository is public and basically open to anybody to contribute).

**Comment by patrikfejda** [comment]
@Sibyx thanks, I translated my comment to English

**Comment by Sibyx** [comment]
Fixed in the [1.5.1](https://github.com/FIIT-Databases/tester/releases/tag/1.5.1)
