### ISSUE TITLE
Show request method

### ISSUE THREAD

**Issue by patrikfejda** [FIIT-Databases/tester#4]
This is more of an impovement proposal than a bug. 

When working on assignment 5 we used GET, PATCH and DELETE requests for the same URI (see pic).

From the scenario detail image I cannot see which type of request is failing.

![image](https://user-images.githubusercontent.com/55843553/235726691-948a6cd5-7057-433e-9747-b567be00c7ef.png)
 
 The information about the failing request method needs to be found in the container output section, which is kinda unpractical:
 
 
![image](https://user-images.githubusercontent.com/55843553/235727160-54b920e2-a0d2-4f8c-869d-0fdcd199914d.png)

**Comment by Sibyx** [comment]
Already in master, will be published with 1.11.0.

![Screenshot 2024-02-10 at 04-03-53 DBS Tester](https://github.com/FIIT-Databases/tester/assets/2022531/82bf689e-5589-4e4d-b907-f65177518054)
