### ISSUE TITLE
Save and prefill image on new test

### ISSUE THREAD

**Issue by patrikfejda** [FIIT-Databases/tester#5]
One more UX improvement proposal, IMO low prio

When testing the app I always start new test on this screen: https://tester-dbs.fiit.stuba.sk/tasks/new
![image](https://user-images.githubusercontent.com/55843553/235727606-d5be1126-c8b1-40af-82a3-d84f75d75b34.png)

And each time I need to input my image url (which basically stays the same for the whole testing process).

A very usefull feature would be some kind of saving the lastly inputed image.

My proposal would be to save the last entered value and prefill this value the next time user loads this screen.

**Comment by Sibyx** [comment]
Hello @patrikfejda,
I am aware that it is not that much comfortable. I wanted to implement something like `Retry` button for the existing test scenario. So instead of creating a new test, you could just hit a button from a previous one. What do you think?

**Comment by patrikfejda** [comment]
Hey @Sibyx 

I dont really think your proposal would solve issue I described.

1) THE RETRY BUTTON IS NOT NEEDED

When I run the test and want to rerun the test again I can get back on browser and hit "SUBMIT". In this case the image uri is cached. So the retry button is a very low priority for me.

One more UX note to the retry button - when I change the image and hit retry button, I (as a user) would be not sure whether the app loads the latest image or not. IMO, this should be shown to the user in some way.


2) I don't think you understood my issue correctly. The flow of this issue is:

- I open browser.
- tester-dubs.fiit.com
- login
- new test

Now the the screen is shown (see above) - and in this screen I would like to see the image url input with prefilled value from the last run. I have concrete idea about the logic for saving the link for prefill, but that should not be a hard task imo.

**Comment by Sibyx** [comment]
Hi @patrikfejda,
kk, why not. That's why i asked. The feature will be implemented as you described. You will be blessed by future generations.

**Comment by Sibyx** [comment]
Already in master, will be published with 1.11.0.
